version: '3.8'
services:
    back:
        image: {{ env.BACKEND_IMAGE }}
        environment:
            - HASH_ROUNDS={{ env.HASH_ROUNDS }}
            - JWT_SECRET={{ env.JWT_SECRET }}
            - PORT=3001
        restart: always

    front:
        image: {{ env.FRONTEND_IMAGE }}
        restart: always
        depends_on:
            - back
        ports:
            - 80:80

volumes:
    main_vol: