version: "3.8"

services:
  deb_db:
    image: postgres:14
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pass
    volumes:
        - main_vol:/var/lib/postgresql/data:rw


volumes:
  main_vol: